project:
  type: website
  output-dir: _site

website:
  title: "Home"
  favicon: files/logo.png
  twitter-card: 
    creator: "@Rilquer"
  cookie-consent: false 
  search: true
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - text: "Research"
        file: research.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Mentoring"
        file: mentoring.qmd
      - text: "CV"
        file: cv.qmd
format:
  html:
    theme: 
      light: spacelab
    css: styles.css
    toc: true

editor: visual